# Generated by Django 6.0.2 on 2026-02-14 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0002_token_date_alter_token_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_from', to='queues.token')),
                ('to_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_to', to='queues.token')),
            ],
        ),
    ]
