# Generated by Django 6.0.2 on 2026-02-14 09:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_token_actual_duration_token_end_time_and_more'),
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 9, 27, 57, 343008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='from_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_sent', to='queues.token'),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='to_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_received', to='queues.token'),
        ),
    ]
