# Generated by Django 6.0.2 on 2026-02-14 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_token_date_alter_token_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=20),
        ),
    ]
