# Generated by Django 6.0.2 on 2026-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_doctor_user_alter_token_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='actual_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
